# DATE - 09/07/2023

# WELCOME TO NUMPY

NumPy (Numerical Python) is an open source Python library that's used in almost every field of science and engineering. It's the universal standard for working with numerical data in Python, and it's at the core of the scientific Python and PyData ecosystems. NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. The NumPy API is used extensively in Pandas. SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

The NumPy library contains multidimensional array and matrix data structures (you'll find more information about this in later sections). It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high- level mathematical functions that operate on these arrays and matrices.

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

# WHAT IS AN ARRAY ?

An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element. and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

Array


An array is a collection of items stored at contiguous memory locations,each identified by at least one array index or key. The idea is to store multiple items of the same type together

In [4]:
import numpy
# this is the pri define laberarry so you have to firstly used IMPORT command (IMPORT NUMPY)

In [5]:
numpy.array([1,2,3]) # integer data

array([1, 2, 3])

In [6]:
numpy.array([15.6,16.1,5.6,3.5]) # float data

array([15.6, 16.1,  5.6,  3.5])

In [7]:
n=numpy.array([1,2,3])

In [8]:
n

array([1, 2, 3])

In [9]:
k=numpy.array([15.8,16.9,18.5,5.6,6.3])
k

array([15.8, 16.9, 18.5,  5.6,  6.3])

In [10]:
n=numpy.array([15,78,15.1,16.8,57,51,100,45.65])   # integer and float both data
n
# in this condition the integer data will change in float data.

array([ 15.  ,  78.  ,  15.1 ,  16.8 ,  57.  ,  51.  , 100.  ,  45.65])

In [11]:
import numpy as np

In [12]:
n=np.array([15,4564,646,465,4,654,64,64,6456])
n

array([  15, 4564,  646,  465,    4,  654,   64,   64, 6456])

NUMPY IS THE BASED ON INDEX VALUES 

In [14]:
#find the values acording to INDEX VALUES
n[0]

15

In [15]:
n[5],n[7],n[3],n[6],n[8]

(654, 64, 465, 64, 6456)

In [16]:
c=np.array([100,200,300,400,500,600,700])
c

array([100, 200, 300, 400, 500, 600, 700])

In [17]:
print(c,end='')

[100 200 300 400 500 600 700]

In [18]:
c.dtype

dtype('int32')

In [19]:
k=np.array([15.6,12.8,14.5,5.6,4.2,6.3])
k

array([15.6, 12.8, 14.5,  5.6,  4.2,  6.3])

In [20]:
k.dtype
# float data type

dtype('float64')

In [21]:
n=np.array([15,16,1.5,7.9,4.5,63,4.9])
n

array([15. , 16. ,  1.5,  7.9,  4.5, 63. ,  4.9])

In [22]:
n.dtype

dtype('float64')

In [23]:
j=np.array([15,25,20.3,17.9,45,12.7,3.6])
j

array([15. , 25. , 20.3, 17.9, 45. , 12.7,  3.6])

In [24]:
print(j)

[15.  25.  20.3 17.9 45.  12.7  3.6]


In [25]:
j.dtype

dtype('float64')

In [26]:
# change the value float to int

j=np.array([15,25,20.3,17.9,45,12.7,3.6],('int32'))
j

array([15, 25, 20, 17, 45, 12,  3])

In [27]:
c=np.array([1,2,3],('int32'))
c

array([1, 2, 3])

In [28]:
c=np.array([1,2,3],('float64'))
c

array([1., 2., 3.])

WHAT IS 'int32' & 'float64' ?

In [29]:
a=np.array([15,85,9,5,78,5,95,6,47,56,63])
a

array([15, 85,  9,  5, 78,  5, 95,  6, 47, 56, 63])

In [30]:
a.size

11

In [31]:
a.itemsize

4

In [32]:
b=np.array([15.2,45.25,6.7,1.9,45.6,34.97,5.6,7.96,100.45])
b

array([ 15.2 ,  45.25,   6.7 ,   1.9 ,  45.6 ,  34.97,   5.6 ,   7.96,
       100.45])

In [33]:
b.size

9

In [34]:
b.itemsize

8

In [35]:
a.dtype

dtype('int32')

In [36]:
b.dtype

dtype('float64')

In [37]:
k=np.array([15,64,87,9,5,97,5,4,5,66,52],('float64'))
k

array([15., 64., 87.,  9.,  5., 97.,  5.,  4.,  5., 66., 52.])

In [38]:
k('int32')

TypeError: 'numpy.ndarray' object is not callable

In [39]:
k=np.array([15,64,87,9,5,97,5,4,5,66,52],('int32'))
k

array([15, 64, 87,  9,  5, 97,  5,  4,  5, 66, 52])

In [40]:
m=np.array([15.78,95.65,2.6,5.9,7.6,41.65,67.4],("int32"))
m

array([15, 95,  2,  5,  7, 41, 67])

In [41]:
b=np.array([6,8,9,100,5,20,18])
b

array([  6,   8,   9, 100,   5,  20,  18])

In [42]:
b.max()

100

In [43]:
b.min()

5

In [44]:
b.dtype

dtype('int32')

In [45]:
b.size

7

In [46]:
b.itemsize
b

array([  6,   8,   9, 100,   5,  20,  18])

In [47]:
b.shape

(7,)

# TWO DIMENSIONAL ARRAY
n=np.array([[c1,c2],[c1,c2]])

In [48]:
n=np.array([[1,2],[3,4]])
n

array([[1, 2],
       [3, 4]])

In [49]:
n.shape

(2, 2)

In [50]:
n.shape

(2, 2)

In [51]:
n.max()

4

In [52]:
n.min()

1

In [53]:
n.size

4

In [54]:
n.itemsize

4

In [55]:
n.dtype

dtype('int32')

In [56]:
28+30+30+30+10

128

In [57]:
n

array([[1, 2],
       [3, 4]])

In [58]:
import numpy as np

In [59]:
n.shape

(2, 2)

# 3 ROW AND 2 COLUMN

In [60]:
j=np.array([[21,45],[16,18],[49,47]])

In [61]:
j

array([[21, 45],
       [16, 18],
       [49, 47]])

In [62]:
j.shape

(3, 2)

In [63]:
j.max(),j.min(),j.dtype,j.shape,j.size

(49, 16, dtype('int32'), (3, 2), 6)

In [64]:
k=np.array([[15,48,78],[45,87,64],[45,13,65]])
k

array([[15, 48, 78],
       [45, 87, 64],
       [45, 13, 65]])

In [65]:
k.shape

(3, 3)

In [66]:
k.max()   , k.min()

(87, 13)

In [67]:
# 5 rows and 3 column

m=np.array([[45,48,74],[45,62,12],[19,72,96],[45,16,38],[45,65,87]])
m

array([[45, 48, 74],
       [45, 62, 12],
       [19, 72, 96],
       [45, 16, 38],
       [45, 65, 87]])

In [68]:
m.shape

(5, 3)

In [69]:
m.ndim

2

In [70]:
n=np.array([[15,45,16,17,89,23,45,44,65,65,66],[45,45,45,78,96,96,78,89,63,42,41]])
n

array([[15, 45, 16, 17, 89, 23, 45, 44, 65, 65, 66],
       [45, 45, 45, 78, 96, 96, 78, 89, 63, 42, 41]])

In [71]:
n.shape

(2, 11)

In [72]:
n.ndim

2

In [73]:
n.max()

96

In [74]:
n.min()

15

# ARANGE FUNCTION =
this is work like range function in python.

In [75]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [76]:
l=np.arange(21)
l

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

# RESHAPE FUNCTION
here you can change the row and column value

In [77]:
h=np.array([[11,12,13],[44,65,86],[87,98,49],[11,12,13]])

In [78]:
h

array([[11, 12, 13],
       [44, 65, 86],
       [87, 98, 49],
       [11, 12, 13]])

In [79]:
h.shape

(4, 3)

In [80]:
# Let's change the 3 x 4 


h.reshape(3,4)


# Set the rows and column in the fectorial of total eliment (if eliments = 12 then (4x3 or 3x4))

array([[11, 12, 13, 44],
       [65, 86, 87, 98],
       [49, 11, 12, 13]])

In [84]:
h.reshape(2,6)

array([[11, 12, 13, 44, 65, 86],
       [87, 98, 49, 11, 12, 13]])

USE ARANGE FUNCTION TO CREATE ARRAY

In [85]:
np.arange(15)
n

array([[15, 45, 16, 17, 89, 23, 45, 44, 65, 65, 66],
       [45, 45, 45, 78, 96, 96, 78, 89, 63, 42, 41]])

In [86]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [87]:
k=np.arange(16)
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [88]:
k.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [90]:
k.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [91]:
m=np.arange(30).reshape(6,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [92]:
nav=np.arange(50).reshape(2,25)
print(nav,end='')

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]]

In [93]:
type(nav)

numpy.ndarray

ZEROS AND ONES FUNCTION

In [94]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
n=np.ones([5,8])
n

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [96]:
n.reshape(10,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# BROADCASTING IN NUMPY
the term broadcasting describes how numpy treats arrays with different shapes during arthemitic operations. subject to certain constraints, the smaller array is broadcast across the larger array so that the have compatible shapes. Brodcasting provides a means of vectorizing array operations.

In [97]:
a=np.array([2,3,4])

b=np.array([2,3,4])

In [98]:
a

array([2, 3, 4])

In [99]:
b

array([2, 3, 4])

In [100]:
a+b

array([4, 6, 8])

In [101]:
a*b

array([ 4,  9, 16])

In [102]:
c=np.array([4])

In [103]:
a*c

array([ 8, 12, 16])

In [104]:
a/c

array([0.5 , 0.75, 1.  ])

In [105]:
b

array([2, 3, 4])

In [106]:
b**2

array([ 4,  9, 16])

In [107]:
a**5

array([  32,  243, 1024], dtype=int32)

RANDOM FUNCTION
  * it's give any random number

In [108]:
np.random.random([2,3])

array([[0.1202032 , 0.8125827 , 0.42505661],
       [0.48788793, 0.98247826, 0.41836702]])

In [109]:
n=np.random . random ([5,3])
n
# it's give any random number 

array([[0.20354493, 0.16315956, 0.1635783 ],
       [0.46309159, 0.13616301, 0.16050925],
       [0.00902508, 0.3871076 , 0.67583312],
       [0.61165278, 0.21895842, 0.66991094],
       [0.62546553, 0.53562183, 0.78959125]])

In [110]:
k=np.ones([5,3])
k

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [111]:
n+k

array([[1.20354493, 1.16315956, 1.1635783 ],
       [1.46309159, 1.13616301, 1.16050925],
       [1.00902508, 1.3871076 , 1.67583312],
       [1.61165278, 1.21895842, 1.66991094],
       [1.62546553, 1.53562183, 1.78959125]])

In [112]:
j=n*k
j

array([[0.20354493, 0.16315956, 0.1635783 ],
       [0.46309159, 0.13616301, 0.16050925],
       [0.00902508, 0.3871076 , 0.67583312],
       [0.61165278, 0.21895842, 0.66991094],
       [0.62546553, 0.53562183, 0.78959125]])

# UNIVERSAL FUNCTION
Mathematics Function

In [113]:
b=np.arange(3)
b

array([0, 1, 2])

In [114]:
np.exp(b)

array([1.        , 2.71828183, 7.3890561 ])

In [115]:
np.arange(2,8)

array([2, 3, 4, 5, 6, 7])

In [116]:
l=np.arange(5,50,5)
l

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [117]:
np.sqrt(l)

array([2.23606798, 3.16227766, 3.87298335, 4.47213595, 5.        ,
       5.47722558, 5.91607978, 6.32455532, 6.70820393])

In [118]:
o=l**2
o

array([  25,  100,  225,  400,  625,  900, 1225, 1600, 2025])

In [119]:
np.sqrt(o)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [120]:
a

array([2, 3, 4])

In [121]:
c=np.array([5,9,6])
np.add(a,c)

array([ 7, 12, 10])

In [122]:
np.add(a,c)

array([ 7, 12, 10])

INDEXING , SLICING, AND ITERATING

In [123]:
a=np.arange(6,30)
a

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29])

In [124]:
a[2]

8

In [125]:
a[-5]

25

In [126]:
a[5:15]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [127]:
a[-15:-5]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [128]:
a[-5:-15] # it's not showing result

array([], dtype=int32)

In [129]:
a[-4:]

array([26, 27, 28, 29])

NAN FUNCTION

  * If you have any missing data then you used nan function

In [130]:
n=np.array([1,np.nan,3,8,9,6,5,np.nan,8,6,4,2,12,34,15])
n

array([ 1., nan,  3.,  8.,  9.,  6.,  5., nan,  8.,  6.,  4.,  2., 12.,
       34., 15.])

The random module provides nice functions to generate random numbers (and also statistical dististical distributions) of any given shape rand function will generate any number between 0 and 1.

RANDOM.RAND FUNCTION

it's work like Random Function

In [131]:
np.random.rand(2,2)

array([[0.59378199, 0.21248223],
       [0.81961373, 0.67885929]])

# RANDN

it's give Negative (-ve) or positive (+ve) result (some negative or some positive result)

In [132]:
np.random.randn(2,3)

array([[ 0.25732062, -0.00322546,  0.10360128],
       [-0.31161966, -0.82719054,  1.31813679]])

In [133]:
np.random.randn(7,9)

array([[-1.26297378, -0.60089294,  0.70452062, -1.06531098,  0.41550792,
         0.67747792,  0.41368206, -0.32085873, -0.22357526],
       [-0.35856848,  1.04198704, -0.16181506,  0.63600993, -1.25565353,
        -0.03584663, -1.48767435, -2.89064794,  1.53157609],
       [ 0.39120012,  1.1869343 , -0.74652969, -0.02006841, -0.18014705,
        -1.68157177,  1.41953034, -1.12343104, -0.48841405],
       [ 0.427669  , -0.45361561, -0.22031997,  0.63438998,  0.14810225,
        -0.85934128,  0.28560835, -0.72299816, -0.73365091],
       [ 0.36077605,  0.29328577, -0.88659558,  0.63406992,  2.34628445,
         0.97735434, -1.11893445, -0.95649615, -1.2321254 ],
       [ 0.48787052, -0.10339694,  0.35640151,  0.71893425, -0.24095537,
        -0.41448127,  0.63234177, -1.55057054,  1.39293198],
       [-1.24169569,  1.28114687, -0.1252484 ,  1.20120704,  0.35283357,
        -0.99697228,  1.20321811, -0.36201669, -0.0980256 ]])